site_name: Docs to Markdown Library
docs_dir: docs
site_dir: site
nav:
  - Home: index.md
  - Converter: converter.md
  - Documents: markdown/index.md
  - Future enhancements: future-enhancements.md
theme:
  name: readthedocs
plugins:
  - search
markdown_extensions:
  - footnotes
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/sidebar-resync.js
  - javascripts/back-button.js
  - javascripts/converter.js?v=8ad0b73
  - javascripts/manage-documents.js
